# Generated by Django 3.2.6 on 2021-08-15 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('M', 'Matric'), ('I', 'Intermediated'), ('G', 'Graduation'), ('P', 'Master')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'name')},
        ),
    ]
